from pathlib import Path
import re

path = Path(__file__).resolve().parents[1] / "index.html"
text = path.read_text(encoding="utf-8")

style = '''<style id="home-community-menu-fix">
.home-community-compact{padding:34px 0 42px;background:#fffaf8}.home-community-compact .container{max-width:1160px}.community-compact-inner{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:22px 28px;border:1px solid #ead8cf;border-radius:18px;background:#fff3ed;box-shadow:0 8px 22px rgba(67,35,27,.05)}.community-compact-copy{display:flex;align-items:baseline;gap:16px;flex-wrap:wrap}.community-compact-copy strong{color:#3b1f1b;font:700 23px/1.1 Playfair Display,Georgia,serif}.community-compact-copy span{color:#806b65;font-size:14px}.community-compact-link{display:inline-flex;align-items:center;gap:8px;flex:0 0 auto;padding:10px 15px;border-radius:999px;background:#e7644d;color:#fff!important;text-decoration:none;font-size:13px;font-weight:800}.community-compact-link:hover{background:#bc4838}#root .main-nav .home-resource-link{color:#715d55}@media(max-width:850px){.community-compact-inner{align-items:flex-start;flex-direction:column;padding:22px}.community-compact-link{width:100%;justify-content:center}.community-compact-copy{display:block}.community-compact-copy span{display:block;margin-top:7px}}
</style>'''

script = '''<script id="home-library-injection">(function(){function addMenuLinks(){var nav=document.querySelector("#root .main-nav");if(!nav)return;var button=nav.querySelector(".nav-button");[["Receitas","/receitas/"],["E-books","/ebooks/"]].forEach(function(item){if(!nav.querySelector('a[href="'+item[1]+'"]')){var a=document.createElement("a");a.className="home-resource-link";a.href=item[1];a.textContent=item[0];if(button)nav.insertBefore(a,button);else nav.appendChild(a)}})}function addLibrary(){var root=document.getElementById("root");if(!root||root.querySelector(".home-library"))return;var community=root.querySelector(".community-section"),footer=root.querySelector(".site-footer");if(!community&&!footer)return;var section=document.createElement("section");section.className="section home-library";section.innerHTML='<div class="container"><div class="home-library-heading"><div><p class="eyebrow">Continue explorando</p><h2>Receitas e ideias para sua confeitaria</h2></div><p>Conteúdo simples para testar na cozinha, organizar a produção e tomar decisões melhores no seu negócio.</p></div><div class="home-library-grid"><a class="home-library-card" href="/receitas/"><span class="resource-mark">R</span><span><h3>Receitas</h3><p>Preparo passo a passo, ingredientes organizados e dicas para produzir.</p></span><span class="resource-arrow" aria-hidden="true">→</span></a><a class="home-library-card" href="/ebooks/"><span class="resource-mark">PDF</span><span><h3>E-books</h3><p>Materiais em PDF para estudar, consultar e ampliar seu repertório.</p></span><span class="resource-arrow" aria-hidden="true">→</span></a></div></div>';if(community)community.parentNode.insertBefore(section,community);else footer.parentNode.insertBefore(section,footer)}function compactCommunity(){var old=document.querySelector("#root .community-section");if(!old||old.dataset.compact)return;if(old.querySelector(".community-card")){old.dataset.compact="true";old.className="home-community-compact";old.innerHTML='<div class="container"><div class="community-compact-inner"><div class="community-compact-copy"><strong>Doce &amp; Lucro</strong><span>Ideias práticas para vender melhor e cuidar do seu lucro.</span></div><a class="community-compact-link" href="https://t.me/docelucro" target="_blank" rel="noopener">Entrar na comunidade <span aria-hidden="true">→</span></a></div></div>'}}function mount(){addMenuLinks();addLibrary();compactCommunity();var root=document.getElementById("root");if(root&&!root.__homeTuningObserver){root.__homeTuningObserver=true;new MutationObserver(function(){addMenuLinks();addLibrary();compactCommunity()}).observe(root,{childList:true,subtree:true})}}mount()})();</script>'''

text = re.sub(r'<script id="home-library-injection">.*?</script>', script, text, count=1, flags=re.S)
if 'id="home-community-menu-fix"' not in text:
    text = text.replace('</head>', style + '</head>', 1)
path.write_text(text, encoding="utf-8")
print('menu da home atualizado, recursos preservados e comunidade compactada')
